### ISSUE TITLE
mmeta archived

### ISSUE THREAD

**Issue by wviechtb** [cran-task-views/MetaAnalysis#3]
The mmeta package has been archived: https://cran.r-project.org/package=mmeta

I would wait a bit to see if it will be revived in the near future - if not, it should be removed (@zeileis  mentioned somewhere that archived packages should not be listed in the task views).

**Comment by zeileis** [comment]
It was in this discussion: https://github.com/cran-task-views/ctv/issues/35#issuecomment-1275264204. But that pertained to including a package in a task view that was archived for a relatively long time already.

In cases like `mmeta` our current strategy is the following:

* We just flag the package as archived on the task view page <https://CRAN.R-project.org/view=MetaAnalysis>.  At the moment the following four packages from the task view are archived: `concurve`, `CopulaDTA`, `mmeta`, `xmeta`.
* If it is still archived after 60 days, then we create an issue in the GitHub repositories of the affected task views.
* If it is still archived after 100 days, we ask to exclude the package from the task view.

The plan is to fully automate this pipeline with cronjobs but we are not there yet. At the moment we trigger the different steps manually "from time to time".

**Comment by wviechtb** [comment]
Thanks for chiming in. Sounds like a good plan!

**Comment by wviechtb** [comment]
It is unarchived, so closing this now.
